Include roadmap.md in source distribution
Fixes the following build error when compiling the test suite from a hackage source checkout:

```
[17 of 21] Compiling Taskell.IO.Markdown.ParserTest ( test/Taskell/IO/Markdown/ParserTest.hs, dist/build/taskell-test/taskell-test-tmp/Taskell/IO/Markdown/ParserTest.dyn_o )

test/Taskell/IO/Markdown/ParserTest.hs:33:19: error:
    • Exception when trying to run compile-time code:
        test/Taskell/IO/data/roadmap.md: openBinaryFile: does not exist (No such file or directory)
      Code: embedFile "test/Taskell/IO/data/roadmap.md"
    • In the untyped splice:
        $(embedFile "test/Taskell/IO/data/roadmap.md")
   |
33 | file = decodeUtf8 $(embedFile "test/Taskell/IO/data/roadmap.md")
   |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```